-- Tabla para almacenar los datos de los clientes
CREATE TABLE Clientess (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    telefono VARCHAR2(20),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla para almacenar los productos
CREATE TABLE Productos (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_producto VARCHAR2(150) NOT NULL,
    descripcion CLOB,
    precio NUMBER(10, 2) NOT NULL,
    stock NUMBER NOT NULL
);

-- Tabla para almacenar la información de los repartidores
CREATE TABLE Repartidores (
    id_repartidor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR2(150) NOT NULL,
    telefono VARCHAR2(20),
    vehiculo_placa VARCHAR2(10)
);

-- Tabla para los pedidos de los clientes
CREATE TABLE Pedidos (
    id_pedido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente NUMBER,
    fecha_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    direccion_envio VARCHAR2(255) NOT NULL,
    ciudad_envio VARCHAR2(100) NOT NULL,
    monto_total NUMBER(10, 2) NOT NULL,
    estado_pago VARCHAR2(50) DEFAULT 'Pendiente',
    CONSTRAINT fk_pedidos_cliente
        FOREIGN KEY (id_cliente) REFERENCES Clientess(id_cliente)
);

-- Tabla de detalle de los pedidos
CREATE TABLE Detalle_Pedidos (
    id_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido NUMBER,
    id_producto NUMBER,
    cantidad NUMBER NOT NULL,
    precio_unitario NUMBER(10, 2) NOT NULL,
    CONSTRAINT fk_detalle_pedido
        FOREIGN KEY (id_pedido) REFERENCES Pedidos(id_pedido),
    CONSTRAINT fk_detalle_producto
        FOREIGN KEY (id_producto) REFERENCES Productos(id_producto)
);

-- Tabla para el seguimiento de los envíos
CREATE TABLE Envios (
    id_envio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido NUMBER,
    id_repartidor NUMBER,
    fecha_despacho TIMESTAMP,
    fecha_entrega_estimada DATE,
    fecha_entrega_real TIMESTAMP,
    estado_envio VARCHAR2(50) DEFAULT 'En almacen',
    CONSTRAINT fk_envios_pedido
        FOREIGN KEY (id_pedido) REFERENCES Pedidos(id_pedido),
    CONSTRAINT fk_envios_repartidor
        FOREIGN KEY (id_repartidor) REFERENCES Repartidores(id_repartidor)
);